# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 20:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='has to be 8 letters', regex='^/w{8}$')]),
        ),
    ]
